name: Create Angular Project

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Name of the Angular project'
        required: true
      repo_name:
        description: 'Name of the new repository'
        required: true

jobs:
  create-project:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install Angular CLI
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      # Create Angular project
      - name: Generate Angular Project
        run: |
          # Cambiar al directorio temporal
          cd /tmp

          # Crear el proyecto Angular
          npx -p @angular/cli ng new ${{ inputs.project_name }} --defaults --skip-git

          # Mover el proyecto generado al directorio de trabajo del runner
          mv ${{ inputs.project_name }} $GITHUB_WORKSPACE/${{ inputs.project_name }}

          # Volver al directorio del flujo de trabajo
          cd $GITHUB_WORKSPACE

      # Create GitHub Repository using API
      - name: Create Repository with API
        run: |
          RESPONSE=$(curl -X POST \
          -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/user/repos \
          -d '{"name":"${{ inputs.repo_name }}","private":true}')
          echo "$RESPONSE"

          # Verificar si el repositorio fue creado correctamente
          if echo "$RESPONSE" | grep '"id":'; then
            echo "Repository created successfully."
          else
            echo "Failed to create repository."
            exit 1
          fi

      # Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      # Initialize Git and Push to Repository
      - name: Push Angular Project to Repository
        run: |
          cd ${{ inputs.project_name }}
          git init
          git add .
          git commit -m "Initial commit for ${{ inputs.project_name }}"

          # Configurar remoto
          git remote remove origin || true

          # Agregar el remoto con autenticación
          git remote add origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository_owner }}/${{ inputs.repo_name }}.git
          # Subir los archivos
          git branch -M main
          git push -u origin main
