name: Create Angular Project

on:
  workflow_dispatch: # Permite iniciar el flujo manualmente
    inputs:
      project_name:
        description: 'Name of the Angular project'
        required: true
      repo_name:
        description: 'Name of the new repository'
        required: true

jobs:
  create-project:
    runs-on: self-hosted # Usa el runner auto-hospedado

    steps:
      # 1. Configurar el entorno
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 2. Instalar Angular CLI
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      # 3. Crear el proyecto Angular
      - name: Generate Angular Project
        run: |
          ng new ${{ inputs.project_name }} --defaults --skip-git
          cd ${{ inputs.project_name }}
          echo "Setting up deployment configuration..."
          echo -e "version: 1\nsteps:\n- name: Deploy" > deployment-pipeline.yml

      # 4. Inicializar Git
      - name: Initialize Git
        run: |
          cd ${{ inputs.project_name }}
          git init
          git add .
          git commit -m "Initial commit for ${{ inputs.project_name }}"

      # 5. Crear el repositorio en GitHub
      - name: Create GitHub Repository
        uses: peter-evans/create-or-update-repository@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: ${{ inputs.repo_name }}
          private: true

      # 6. Subir el proyecto al repositorio
      - name: Push to GitHub
        run: |
          cd ${{ inputs.project_name }}
          git remote add origin https://github.com/${{ github.repository_owner }}/${{ inputs.repo_name }}.git
          git branch -M main
          git push -u origin main
