name: Deploy Angular Application

on:
  push:
    branches:
      - main

jobs:
  deploy-to-docker:
    runs-on: self-hosted

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install dependencies and build the Angular app
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Angular Application
        run: npm run build -- --configuration=production

      # Build and push Docker image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest

      # Deploy to Docker server
      - name: Deploy to Docker Server
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest
          docker stop ${{ vars.CONTAINER_NAME }} || true
          docker rm ${{ vars.CONTAINER_NAME }} || true
          docker run -d --name ${{ vars.CONTAINER_NAME }} -p ${{ vars.PORT }}:80 ${{ secrets.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest
          EOF
